name: Build For Windows

on: 
  workflow_dispatch: {}
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
        
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: jyx2/Packages
          key: Packages-${{ hashFiles('Packages/packages-lock.json') }}
          restore-keys: |
            Packages-

      # Build
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildMethod: Jyx2Editor.BuildTool.Jyx2BuildTool.BuildForWindows
          projectPath: jyx2
          buildsPath: jyx2/build
      
      # Zip packages
      - name: Zip Builds
        uses: vimtor/action-zip@v1
        with: 
          files: jyx2/build
          dest: ${{steps.build.outputs.buildVersion}}-jynew-windows64.zip
          recursive: true
          
      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ${{steps.build.outputs.buildVersion}}-jynew-windows64.zip
